POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer aaa

{
    "title": "Test Authorization",
    "author": "Terry Alman",
    "url": "www.terryalaman.com",
    "likes": 50
}